- name: Disable swap
  command: swapoff -a
  when: ansible_virtualization_role == "guest"

- name: Remove swap entry from fstab
  replace:
    path: /etc/fstab
    regexp: '^.* swap .*$'
    replace: ''
  when: ansible_virtualization_role == "guest"

- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Enable Docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Add Kubernetes APT key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes repo
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main

- name: Install kubeadm, kubelet and kubectl
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes

- name: Hold Kubernetes packages
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    mark: hold
