

- name: Kubernetes Master Setup
  hosts: k8s_master
  become: yes
  roles:
    - role: k8s_master

- name: Kubernetes Worker Setup
  hosts: k8s_workers
  become: yes
  roles:
    - role: k8s_workers
